### ISSUE TITLE
Calificación de infografia

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/infografia-de-las-librerias-Gregorio012#3]
Esta práctica obtuvo 98% 
Correspondiente a **19.6** de calificación
[funciones de una librería (1).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Gregorio012/files/8350892/funciones.de.una.libreria.1.pdf)

**Comment by josealfredo79** [comment]
bien hecho...y revisado...
